import 'tailwindcss/tailwind.css'

import React from "react";
import { AuthProvider } from "../src/contexts/Auth";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type IProps = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: IProps) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
